// Self-simulation loop.
//
// For each generation g = 1..MAX_GEN (one "loop"):
//   1. Activate gen g's NEW evals on top of all previous gens (comprehensive).
//   2. Self-play thousands of games and hill-climb the tuning to satisfy the
//      now-larger eval set — i.e. learn from what works and what doesn't.
//   3. Re-run the full comprehensive review and record what changed.
//
// Outputs:
//   tuned.json          — the winning tuning the phone game loads.
//   IMPROVEMENT_LOG.md  — human-readable story of each loop.
//   loop-results.json   — machine-readable record of every loop.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { TUNING } from "../src/engine.js";
import { evalsUpToGen, MAX_GEN } from "../evals/evals.js";
import { optimize } from "./optimize.js";

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dir, "..");

function pct(x) {
  return `${(x * 100).toFixed(0)}%`;
}

function run() {
  let tuning = JSON.parse(JSON.stringify(TUNING));
  const loops = [];

  for (let gen = 1; gen <= MAX_GEN; gen++) {
    const evals = evalsUpToGen(gen);
    const newIds = evals.filter((e) => e.gen === gen).map((e) => e.id);

    // Score before optimizing (carry-over tuning from the previous loop).
    const before = optimize(tuning, evals, { steps: 0 }).eval;

    // Learn: search for tuning that best satisfies the expanded eval set.
    const res = optimize(tuning, evals, { steps: 260, seed: gen * 17 + 1 });
    tuning = res.tuning;

    const after = res.eval;
    loops.push({
      gen,
      newEvals: newIds,
      totalEvals: evals.length,
      before: { passed: before.passed, score: before.meanScore },
      after: { passed: after.passed, score: after.meanScore },
      results: after.results.map((r) => ({
        id: r.id,
        gen: r.gen,
        pass: r.pass,
        score: Number(r.score.toFixed(3)),
        detail: r.detail,
      })),
      keyMoves: res.trace.slice(-6),
    });

    console.log(
      `loop ${gen}: +[${newIds.join(", ")}]  ${evals.length} evals  ` +
        `passed ${before.passed}->${after.passed}/${evals.length}  ` +
        `health ${pct(before.meanScore)}->${pct(after.meanScore)}`,
    );
  }

  // Persist the tuned config the game ships with.
  writeFileSync(join(ROOT, "tuned.json"), JSON.stringify(tuning, null, 2));
  writeFileSync(
    join(ROOT, "loop-results.json"),
    JSON.stringify({ generatedAt: new Date().toISOString(), loops, tuning }, null, 2),
  );
  writeFileSync(join(ROOT, "IMPROVEMENT_LOG.md"), renderLog(loops, tuning));
  console.log("\nWrote tuned.json, loop-results.json, IMPROVEMENT_LOG.md");
}

function renderLog(loops, tuning) {
  const out = [];
  out.push("# Self-Improvement Log");
  out.push("");
  out.push(
    "Generated by `node loop/run.js`. Each loop activates a **new generation of " +
      "evals** while re-running every earlier generation, then hill-climbs the " +
      "game tuning to satisfy the comprehensive set. This file is the record of " +
      "what the loop learned.",
  );
  out.push("");
  for (const L of loops) {
    out.push(`## Loop ${L.gen} — added evals: ${L.newEvals.map((e) => `\`${e}\``).join(", ")}`);
    out.push("");
    out.push(
      `Eval set grew to **${L.totalEvals}**. Passing **${L.before.passed} → ${L.after.passed}** / ${L.totalEvals}; ` +
        `health **${pct(L.before.score)} → ${pct(L.after.score)}**.`,
    );
    out.push("");
    out.push("| eval | gen | result | score | detail |");
    out.push("| --- | --- | --- | --- | --- |");
    for (const r of L.results) {
      out.push(
        `| ${r.id} | ${r.gen} | ${r.pass ? "✅" : "❌"} | ${(r.score * 100).toFixed(0)}% | ${r.detail} |`,
      );
    }
    out.push("");
    if (L.keyMoves.length) {
      out.push("**What the loop learned (top tuning moves):**");
      out.push("");
      for (const m of L.keyMoves) {
        out.push(
          `- \`${m.path}\`: ${Number(m.from).toFixed(3)} → ${Number(m.to).toFixed(3)} (health ${pct(m.score)})`,
        );
      }
      out.push("");
    }
  }
  out.push("## Final tuned configuration");
  out.push("");
  out.push("```json");
  out.push(JSON.stringify(tuning, null, 2));
  out.push("```");
  out.push("");
  return out.join("\n");
}

run();
